---
# Playbook to do a simple NGINX install
# Only supports centos!
#
# vars:
#  - elb_instance_name: 'Name' tag of your ELB
#  - deployment_region: region that EC2 instances will reside in
#

- name: Setting up nginx repository
  copy:
    dest: /etc/yum.repos.d/nginx.repo
    content: |
      [nginx]
      name=nginx repo
      baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck=0
      enabled=1

- name: Installing NGINX
  yum:
    name: nginx
    state: present

# TODO: If needed we can use these to edit the NGINX config!
# - name: Copy NGINX configuration to NGINX EC2
#   copy:
#     src: nginx.conf
#     dest: /etc/nginx

# - name: Copy server configuration to NGINX EC2
#   copy:
#     src: example
#     dest: /etc/nginx/conf.d

- name: Clean html destination
  shell: rm -rf /usr/share/nginx/html/*
  changed_when: False

- name: Insert application
  git: 
    repo=https://github.com/pixelsign/html5-device-mockups.git
    dest=/usr/share/nginx/html
    force=yes

- name: Starting NGINX
  service:
    name: nginx
    state: started

- name: Gathering ec2 facts...
  action: ec2_facts

- name: Register ELB to the NGINX EC2
  local_action:
    module: ec2_elb
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: "{{ elb_instance_name }}"
    region: "{{ deployment_region }}"
    state: 'present'