---
# Example Ansible Playbook to deploy a simple HTML5 application on AWS.
#
# Documentation:
#  - EC2: http://docs.ansible.com/ansible/ec2_module.html
#
# Application: https://github.com/pixelsign/html5-device-mockups

- hosts: localhost
  
  vars: 
    

  tasks: 
    - include: roles/stack/stack_creator.yml
      vars:
        nginx_instance_name: "chuck-demo-nginx"
        app_instance_name: "chuck-demo-app"
        elb_instance_name: "chuck-demo-elb"
        deployment_region: "eu-west-1"
    # TODO: gets the address for an EC2 instance
    - include: roles/nginx/ec2_address.yml
      vars:
        instance_name: chuck-demo-nginx
        ssh_name: chuck-demo
        ssh_location: /Users/charlesrice/.ssh/
