---
# Example Ansible Playbook to deploy a simple HTML5 application on AWS.
#
# Documentation:
#  - EC2: http://docs.ansible.com/ansible/ec2_module.
#  - ELB: http://docs.ansible.com/ansible/ec2_elb_lb_module.html
#  - EC2_ELB: http://docs.ansible.com/ansible/ec2_elb_module.html
#  - Aurthorized Keys: http://docs.ansible.com/ansible/authorized_key_module.html
#  - add_hosts: http://docs.ansible.com/ansible/add_host_module.html
#
# Nginx module: 
# Application: https://github.com/pixelsign/html5-device-mockups

- hosts: localhost

  vars: 
    
  tasks: 
    - include: roles/stack/stack_creator.yml
      vars:
        nginx_instance_name: "chuck-demo-nginx"
        app_instance_name: "chuck-demo-app"
        elb_instance_name: "chuck-demo-elb"
        deployment_region: "eu-west-1"

    # Add the nginx EC2 address
    - include: roles/common/ec2_address.yml
      vars:
        instance_name: chuck-demo-nginx
        ssh_name: chuck-demo
        ssh_location: /Users/charlesrice/.ssh/

    # Add the App EC2 address - will export temporary EC2 addresses below {instance_name}.server
    - include: roles/common/ec2_address.yml
      vars:
        instance_name: chuck-demo-app
        ssh_name: chuck-demo
        ssh_location: /Users/charlesrice/.ssh/

    - name: Add SSH key for configuration connections
      authorized_key: user=charlesrice key="{{ lookup('file', '/Users/charlesrice/.ssh/id_rsa.pub') }}"

# "Setup the nginx EC2 instance
- hosts: chuck-demo-nginx.server
  remote_user: root

  tasks:
  #   - shell: echo "Hello world from NGINX server!"
  #   - name: NGINX | Installing NGINX repo rpm
  #     yum:
  #       name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
     
    - name: NGINX | Installing NGINX
      yum:
        name: nginx
        state: latest
     
    - name: NGINX | Starting NGINX
      service:
        name: nginx
        state: started

# Setup the application EC2 instance
- hosts: chuck-demo-app.server
  remote_user: ec2-user
  tasks:
    - shell: echo "Hello world from APP server!"
    # - include: roles/application/application.yml
      # vars:

