---
# Playbook to login and configure the EC2 instance as an nginx server.
# To be used as an include yaml, using the vars:
#  - ec2_address: public DNS
#
#

- hosts: localhost

  vars:
    nginx_name: chuck-demo-nginx
  tasks:
    - shell: aws ec2 describe-instances --filters Name=tag:Name,Values="{{nginx_name}}" # First get the instance information
      register: nginx_info
    - shell: echo "{{ (nginx_info.stdout|from_json).Reservations[0].Instances[0].PublicDnsName }}"
      register: nginx_ec2_address
    - shell: ssh -i ~/.ssh/chuck-demo.pem ec2-user@{{ nginx_ec2_address.stdout }}
